language: node_js

node_js:
  - "7.6.0"

env:
  - NODE_ENV=development

services:
  - memcached
  - mysql

addons:
  hosts:
  - local.itranswarp.com

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;"
  - mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password');"

install:
  - cd www
  - npm install -g mocha
  - npm install

script:
  - mocha


